apiVersion: v1
kind: Service
metadata:
  labels:
    app: database-mysql
  name: database-mysql
spec:
  type: LoadBalancer
  externalIPs:
  - 192.168.49.2
  ports:
  - protocol: "TCP"
    name: "database-mysql-service"
    port: 3360
    targetPort: 3360
    nodePort: 30360
  selector:
    app: database-mysql

