apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: database-mysql
  name: database-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database-mysql
  template:
    metadata:
      labels:
        app: database-mysql
    spec:
      containers:
      - name: mysql
        image: mysql:8.0-debian # related: https://github.com/docker-library/mysql/issues/1055
        imagePullPolicy: IfNotPresent
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password
        ports:
        - containerPort: 3360
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim

