apiVersion: v1
kind: Service
metadata:
  labels:
    app: redis
  name: redis
spec:
  type: LoadBalancer
  externalIPs:
  - 192.168.49.2
  ports:
  - protocol: "TCP"
    name: "redis-service"
    port: 6379
    targetPort: 6379
    nodePort: 30379
  selector:
    app: redis

