apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: redis
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - image: redis:alpine
        name: redis
        command:
          - redis-server
          - "/redis-master/redis.conf"
        env:
          # related: create secret for redis
          # sh -c 'kubectl create secret generic redis-pass --from-literal=password=THE_REDIS_PASSWORD'
          - name: REDIS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: redis-pass
                key: password
        resources:
          requests:
            cpu: '0.5'
            memory: 1Gi
            # storage: '8Gi'
          limits:
            cpu: '1'
            memory: 2Gi
        ports:
        - containerPort: 6379
          name: redis
          # port: 6379
          # protocol: TCP
        volumeMounts:
        - mountPath: /config
          name: redis-config
        - mountPath: /data
          name: redis-data
      volumes:
      - name: redis-data
        emptyDir: {}
      - name: redis-config
        configMap:
          name: redis-config
          items:
          - key: redis-config
            path: redis.conf
