apiVersion: v1
kind: Service
metadata:
  name: webapp-service
spec:
  type: LoadBalancer
  externalIPs:
  - 192.168.49.2
  ports:
  - name: http
    port: 9090
    targetPort: 9090
    nodePort: 30090
  selector:
    app: webapp
